import 'package:flutter/material.dart';

import 'package:zenvix/core/models/tool_definition.dart';
import 'package:zenvix/core/theme/app_colors.dart';

final List<ToolDefinition> registeredTools = [
  // ── PDF Tools ─────────────────────────────────────────────────────────
  const ToolDefinition(
    id: 'pdf_viewer',
    title: 'PDF Viewer',
    description: 'Browse and read any PDF file',
    icon: Icons.picture_as_pdf_rounded,
    accentColor: AppColors.neonBlue,
    secondaryColor: AppColors.accentCyan,
    routePath: '/pdf-viewer',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'image_to_pdf',
    title: 'Image → PDF',
    description: 'Convert images to polished PDFs',
    icon: Icons.image_outlined,
    accentColor: AppColors.neonBlue,
    secondaryColor: AppColors.electricPurple,
    routePath: '/image-to-pdf',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_combiner',
    title: 'PDF Combiner',
    description: 'Merge multiple PDFs into one',
    icon: Icons.merge_type_outlined,
    accentColor: AppColors.electricPurple,
    secondaryColor: AppColors.accentPink,
    routePath: '/pdf-combiner',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_page_manager',
    title: 'Page Manager',
    description: 'Reorder, rotate, delete PDF pages',
    icon: Icons.pages_outlined,
    accentColor: AppColors.accentPink,
    secondaryColor: AppColors.warning,
    routePath: '/pdf-page-manager',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_compression',
    title: 'PDF Compress',
    description: 'Reduce PDF size, preserve quality',
    icon: Icons.compress_rounded,
    accentColor: AppColors.success,
    secondaryColor: AppColors.accentCyan,
    routePath: '/pdf-compression',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_security',
    title: 'PDF Security',
    description: 'Add or remove password protection',
    icon: Icons.lock_outline,
    accentColor: AppColors.electricPurple,
    secondaryColor: AppColors.accentPink,
    routePath: '/pdf-security',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_watermark',
    title: 'PDF Watermark',
    description: 'Stamp text or image on every page',
    icon: Icons.branding_watermark_rounded,
    accentColor: AppColors.accentCyan,
    secondaryColor: AppColors.neonBlue,
    routePath: '/pdf-watermark',
    category: ToolCategory.pdf,
  ),
  const ToolDefinition(
    id: 'pdf_to_image',
    title: 'PDF → Image',
    description: 'Extract pages as images',
    icon: Icons.broken_image_outlined,
    accentColor: AppColors.accentCyan,
    secondaryColor: AppColors.neonBlue,
    routePath: '/pdf-to-image',
    category: ToolCategory.pdf,
    isAvailable: false,
  ),

  // ── Documents & Sheets ────────────────────────────────────────────────
  const ToolDefinition(
    id: 'text_viewer',
    title: 'Text Viewer',
    description: 'Open .txt, .json, .xml, .md files',
    icon: Icons.text_snippet_outlined,
    accentColor: AppColors.warning,
    secondaryColor: AppColors.accentCyan,
    routePath: '/text-viewer',
    category: ToolCategory.documents,
  ),
  const ToolDefinition(
    id: 'ocr_text_extractor',
    title: 'Text Extractor',
    description: 'Extract text from images and PDFs',
    icon: Icons.document_scanner_outlined,
    accentColor: AppColors.neonBlue,
    secondaryColor: AppColors.electricPurple,
    routePath: '/ocr',
    category: ToolCategory.documents,
    isAvailable: false,
  ),

  // ── Utilities ─────────────────────────────────────────────────────────
  const ToolDefinition(
    id: 'qr_tools',
    title: 'QR Tools',
    description: 'Scan and generate QR codes',
    icon: Icons.qr_code_2_outlined,
    accentColor: AppColors.warning,
    secondaryColor: AppColors.accentCyan,
    routePath: '/qr-tools',
    category: ToolCategory.utilities,
  ),
  const ToolDefinition(
    id: 'notes_vault',
    title: 'Notes Vault',
    description: 'Secure encrypted notes storage',
    icon: Icons.lock_outline,
    accentColor: AppColors.accentPink,
    secondaryColor: AppColors.electricPurple,
    routePath: '/notes-vault',
    category: ToolCategory.utilities,
    isAvailable: false,
  ),
];
